# Generated by Django 4.0.4 on 2022-05-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogoForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pName', models.CharField(max_length=50, verbose_name='عنوان پروژه:')),
                ('cName', models.CharField(max_length=50, verbose_name='نام مشتری:')),
                ('bName', models.CharField(max_length=50, verbose_name='نام برند:')),
                ('service', models.CharField(max_length=50, verbose_name='خدمت/سرویس/محصول:')),
                ('wPhone', models.TextField(verbose_name='شماره تماس کسب و کار:')),
                ('pPhone', models.TextField(verbose_name='تماس:')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='ایمیل')),
                ('sAddress', models.TextField(verbose_name='آدرس شبکه های اجتماعی:')),
                ('bExplain', models.TextField(verbose_name='شما چکار میکنید ؟ شغلتون رو توضیح بدید ؟ چه چیزی شغل شما رو منحصر به فرد یا متمایز میکنه ؟')),
                ('gExplain', models.TextField(verbose_name='سعی دارید به چه کسانی دسترسی پیدا کنید؟ هدفتون چه کسانی هستند ؟')),
                ('nameInLogo', models.TextField(verbose_name='چه نامی باید در لوگو درج شود ؟')),
                ('tags', models.TextField(verbose_name='تگ لاین/برچسب')),
                ('isdExplain', models.TextField(verbose_name='در صورت نیاز / وجود چه تصاویری باید در لوگو گنجانده شود ؟')),
                ('isd', models.TextField(verbose_name='تصویری/اشکال/طراحی')),
                ('usage', models.TextField(verbose_name='مارک/برند تجاری، کارت ویزیت و غیره')),
                ('recommendation', models.TextField(verbose_name='طراحی چند اتوده')),
                ('logoType', models.TextField(verbose_name='لوگو تصویری لوگو نوشتاری(فارسی یا انگلیسی) یا تلفیقی باشد؟')),
                ('colorType', models.TextField(verbose_name=' به صورت پیشفرض سیاه سفید است مگر اینکه برند شما رنگ خاصی داشته باشد')),
                ('example', models.TextField(verbose_name=' آیا نمونه خارجی یا داخلی که میخواهید لوگوی خود از آن نمونه برداری شود دارید؟')),
                ('logomotion', models.TextField(verbose_name='نیاز به لوگو موشن دارید؟')),
                ('budget', models.TextField(verbose_name='راه های ارتباطی')),
            ],
        ),
    ]
