# Generated by Django 4.0.4 on 2022-04-20 22:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('workName', models.CharField(max_length=80)),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='شماره تماس وارد شده صحیح نمی باشد.', regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=b'I01\n', max_length=254)),
                ('socialName', models.TextField(blank=True)),
                ('subject', models.CharField(blank=True, max_length=120)),
                ('message', models.TextField()),
            ],
        ),
    ]
