# Generated by Django 4.0.4 on 2022-04-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='email',
            field=models.EmailField(blank=b'I01\n', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='socialName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='subject',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
