# Generated by Django 4.0.4 on 2022-04-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_index_email_alter_index_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
