# Generated by Django 4.0.4 on 2022-04-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_index_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='index',
            name='workName',
            field=models.CharField(max_length=80, verbose_name='نام کسب و کار'),
        ),
    ]
