# Generated by Django 4.0.4 on 2022-04-21 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_index_name_alter_index_workname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='email',
            field=models.EmailField(blank=b'I01\n', max_length=254, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='index',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='متن پیام'),
        ),
        migrations.AlterField(
            model_name='index',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='شماره تماس وارد شده صحیح نمی باشد.', regex='^\\+?1?\\d{9,15}$')], verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='index',
            name='socialName',
            field=models.TextField(blank=True, null=True, verbose_name='رسانه های کسب و کار'),
        ),
        migrations.AlterField(
            model_name='index',
            name='subject',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='موضوع'),
        ),
    ]
