# Generated by Django 4.0.4 on 2022-05-08 17:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_alter_index_email_alter_index_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(code='invalid_phoneNumber', message='شماره تماس وارد شده صحیح نمی باشد.', regex='^\\+?1?\\d{9,15}$')], verbose_name='شماره تماس'),
        ),
    ]
