# Generated by Django 4.0.4 on 2022-04-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.TextField(verbose_name='چالش شرکت')),
                ('dates', models.TextField(verbose_name='تاریخ انجام پروژه')),
                ('moreExplain', models.TextField(verbose_name='توضیحات بیشتر درباره پروژه')),
                ('results', models.TextField(verbose_name='اهداف و نتایج پروژه')),
                ('prjRequirements', models.TextField(verbose_name='الزامات پروژه')),
                ('wyLike', models.TextField(verbose_name='ترجیحات پروژه')),
                ('limits', models.TextField(verbose_name='محدودیت های پروژه')),
                ('goals', models.TextField(verbose_name='اهداف اولیه پروژه')),
                ('measurement', models.TextField(verbose_name='روش های سنجش پروژه')),
                ('Audience', models.TextField(verbose_name='مخاطب های پروژه')),
                ('problems', models.TextField(verbose_name='مشکلات پیاده سازی پروژه')),
            ],
        ),
    ]
