# Generated by Django 4.0.4 on 2022-04-29 21:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projectForm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectform',
            name='Introduction',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='معرفی خود'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectform',
            name='connection',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='راه های ارتباطی'),
            preserve_default=False,
        ),
    ]
