# Generated by Django 4.0.4 on 2022-04-29 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectForm', '0002_projectform_introduction_projectform_connection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectform',
            old_name='Audience',
            new_name='audience',
        ),
        migrations.RenameField(
            model_name='projectform',
            old_name='Introduction',
            new_name='introduction',
        ),
    ]
